In [ ]:
pip install db-sqlite3

Collecting db-sqlite3
  Downloading db-sqlite3-0.0.1.tar.gz (1.4 kB)
  Preparing metadata (setup.py) ... done
Collecting db (from db-sqlite3)
  Downloading db-0.1.1.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... done
Collecting antiorm (from db->db-sqlite3)
  Downloading antiorm-1.2.1.tar.gz (171 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.0/172.0 kB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: db-sqlite3, db, antiorm
  Building wheel for db-sqlite3 (setup.py) ... done
  Created wheel for db-sqlite3: filename=db_sqlite3-0.0.1-py3-none-any.whl size=1770 sha256=fe0ac854999d768a500a54fde664296fe68b2c4a1aef1ea590fa93a486de37ca
  Stored in directory: /root/.cache/pip/wheels/a6/b7/83/e941e0a0e04f417982e718ae7295d1e82b5f2863a1c51edd71
  Building wheel for db (setup.py) ... done
  Created wheel for db: filename=db-0.1.1-py3-none-any.whl size=3874 sha256=08d50ddab4144b7e5a4a3c1b2e36aaa553e3fee93ed2cc6c6451305493123005
  Stored in directory: /root/.cache/pip/wheels/7d/e4/df/bc55b93af204ab098d9effec76f6889ad12d7ad74e833c4910
  Building wheel for antiorm (setup.py) ... done
  Created wheel for antiorm: filename=antiorm-1.2.1-py3-none-any.whl size=31665 sha256=535772d77cf1b36a9c9f256e05cef47c466e7f48244efef7ed867b8c3f978081
  Stored in directory: /root/.cache/pip/wheels/30/9f/7e/b7c95b391cfa77a9e722d359e9c669cf6c8d798d748aec5091
Successfully built db-sqlite3 db antiorm
Installing collected packages: antiorm, db, db-sqlite3
Successfully installed antiorm-1.2.1 db-0.1.1 db-sqlite3-0.0.1

In [ ]:

import pandas as pd
import sqlite3 as sql

In [ ]:
conn = sql.connect("/content/sql-murder-mystery.db")
type(conn)

sqlite3.Connection

In [ ]:
query = """
SELECT * FROM crime_scene_report WHERE city="SQL City" ORDER BY date; """

pd.set_option('display.max_colwidth',None)  # It is used to see the complete statements in description column.
pd.read_sql_query(query,conn)

,date,type,description,city
0,20170712,theft,"A lone hunter stalks the night, firing arrows into the Darkness.\n There is no hiding, no escape. In the distance, the beast\n falters, tethered to the void. The killing blow comes without\n hesitation, without mercy.",SQL City
1,20170820,arson,"Wield the Hammer of Sol with honor, Titan, it is a thing of\n legend, both past and future.",SQL City
2,20171110,robbery,"The Gjallarhorn shoulder-mounted rocket system was forged from\n the armor of Guardians who fell at the Twilight Gap. Gifted\n to the survivors of that terrible battle, the Gjallarhorn\n is seen as a symbol of honor and survival.",SQL City
3,20180103,bribery,"Apparently, Cayde thought it necessary to expose this extremely\n rare vegetable to a Hive summoning ritual.",SQL City
4,20180115,assault,"Hamilton: Lee, do you yield? Burr: You shot him in the side! Yes he yields!",SQL City
5,20180115,assault,Report Not Found,SQL City
6,20180115,murder,"Security footage shows that there were 2 witnesses. The first witness lives at the last house on ""Northwestern Dr"". The second witness, named Annabel, lives somewhere on ""Franklin Ave"".",SQL City
7,20180215,murder,REDACTED REDACTED REDACTED,SQL City
8,20180215,murder,Someone killed the guard! He took an arrow to the knee!,SQL City

In [ ]:
# To get names of the all tables from database.
query = """ SELECT name
            FROM sqlite_master
            WHERE type="table" ; """
pd.read_sql_query(query,conn)

                     name
0      crime_scene_report
1         drivers_license
2                  person
3  facebook_event_checkin
4               interview
5      get_fit_now_member
6    get_fit_now_check_in
7                  income
8                solution

In [ ]:
# To get structure of the crime_scene_report .
query = """SELECT sql
           FROM sqlite_master
           WHERE name="crime_scene_report"; """
pd.read_sql_query(query,conn)

                                                                                                                                 sql
0  CREATE TABLE crime_scene_report (\n        date integer,\n        type text,\n        description text,\n        city text\n    )

In [ ]:
# According to the information provided in crime_scene_report next we need to check person table.
query = """ SELECT * FROM person WHERE address_street_name = "Franklin Ave"; """

#query = """ SELECT * FROM person WHERE address_street_name = "Northwestern Dr" ORDER BY address_number; """
pd.read_sql_query(query,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,12207,Wilmer Wolever,509484,139,Franklin Ave,636825374
1,16371,Annabel Miller,490173,103,Franklin Ave,318771143
2,17683,Johnnie Schee,968887,1277,Franklin Ave,815977821
3,18651,Carleen Etoll,356746,22,Franklin Ave,193369255
4,22636,Zachary Ybarbo,768359,785,Franklin Ave,285346605
5,24737,Gema Nantz,273410,3968,Franklin Ave,180545802
6,30654,Clarita Rickels,418084,2254,Franklin Ave,714941023
7,32264,Shelby Dezeeuw,735415,1391,Franklin Ave,143197463
8,33793,Amado Mattan,161915,99,Franklin Ave,125205748
9,34592,Cordell Lindamood,592762,3657,Franklin Ave,509890333
10,36328,Domenic Laun,971080,3809,Franklin Ave,825329637
11,36400,Noe Pancoast,895755,3443,Franklin Ave,732212073
12,37616,Katelyn Schwerin,430143,332,Franklin Ave,392365033
13,46827,Bev Billiter,643591,2316,Franklin Ave,940192302
14,52059,Jordan Pelton,686854,2786,Franklin Ave,676224073
15,52075,Ezra Phy,928109,384,Franklin Ave,176404498
16,52121,Yelena Whitler,427830,3185,Franklin Ave,115106155
17,54817,Guy Bustard,213929,591,Franklin Ave,820850670
18,54896,Patty Wamsley,688488,1097,Franklin Ave,725272037
19,56142,William Shiver,741336,1926,Franklin Ave,219913461
20,57051,Lavette Koehl,137365,2284,Franklin Ave,776046786
21,59746,Ronny Gumbert,469722,3197,Franklin Ave,561067477
22,60944,Ricki Bidding,443364,2072,Franklin Ave,614976330
23,61001,Laurine Bousman,197150,247,Franklin Ave,431360364
24,61437,Colette Hollomon,661377,453,Franklin Ave,314956038
25,62292,Isaiah Holsten,913856,747,Franklin Ave,995368430
26,62520,Mariah Lepetich,450447,3086,Franklin Ave,797745632
27,67292,Renita Roperto,801041,625,Franklin Ave,894442480
28,69719,Hope Arzabala,311724,841,Franklin Ave,270289620
29,70050,Whitney Herkenratt,138462,3445,Franklin Ave,552518972
30,75510,Sebastian Ramnarase,333188,1127,Franklin Ave,315716580
31,76128,Ressie Razze,633497,1199,Franklin Ave,456366143
32,78170,Graig Summy,192325,3387,Franklin Ave,277793306
33,78408,Dante Eschen,218173,3447,Franklin Ave,135374633
34,78658,Blake Chrones,310242,2014,Franklin Ave,423048084
35,78830,Candice Train,814779,3255,Franklin Ave,717570815
36,83003,Wilmer Casella,672050,3564,Franklin Ave,569057540
37,83754,Maria Walsh,201334,2716,Franklin Ave,121282864
38,84531,Edgar Mendieta,315790,3881,Franklin Ave,458847132
39,87521,Moses Ikerd,638991,2283,Franklin Ave,797715435
40,88966,Raul Eads,570927,2066,Franklin Ave,764132739
41,93947,Omer Andreoni,605718,13,Franklin Ave,322594288
42,95119,Hong Lisa,825828,375,Franklin Ave,113438176
43,97913,Cameron Dilick,971988,2954,Franklin Ave,665147939
44,98744,Jordan Myntti,256116,3104,Franklin Ave,876030104

In [ ]:
# According to the description of the murder the 1st witness is Morty Schapiro and id 14887. So for further info we retrived interview of that person.
query = """ SELECT * FROM interview WHERE person_id = 14887;"""
pd.read_sql_query(query,conn)

,person_id,transcript
0,14887,"I heard a gunshot and then saw a man run out. He had a ""Get Fit Now Gym"" bag. The membership number on the bag started with ""48Z"". Only gold members have those bags. The man got into a car with a plate that included ""H42W""."

In [ ]:
# According to the description of the murder the 2nd witness is Annabel Miller and id 	16371. So for further info we retrived interview of that person.
query = """ SELECT * FROM interview WHERE person_id = 16371;"""
pd.read_sql_query(query,conn)

,person_id,transcript
0,16371,"I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th."

In [ ]:
# Based on the transcript of the 1st witness we have retrived GET FIT NOW GYM table.
query = """SELECT * FROM get_fit_now_member WHERE membership_status = "gold" and id like '48Z%';"""
pd.read_sql_query(query,conn)

      id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

Suspect 1 Name = Joe Germuska
Suspect 2 Name = Jeremy Bowers

In [ ]:
# Based on the transcript of the 2nd witness we have retrived GET FIT NOW GYM table.
query = """SELECT * FROM get_fit_now_check_in WHERE check_in_date = 20180109 ORDER BY check_in_date;"""
pd.read_sql_query(query,conn)

  membership_id  check_in_date  check_in_time  check_out_time
0         X0643       20180109            957            1164
1         UK1F2       20180109            344             518
2         XTE42       20180109            486            1124
3         1AE2H       20180109            461             944
4         6LSTG       20180109            399             515
5         7MWHJ       20180109            273             885
6         GE5Q8       20180109            367             959
7         48Z7A       20180109           1600            1730
8         48Z55       20180109           1530            1700
9         90081       20180109           1600            1700

In [ ]:
# Checking car details.
query = """SELECT * FROM drivers_license WHERE plate_number like '%H42W%';"""
pd.read_sql_query(query,conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,183779,21,65,blue,blonde,female,H42W0X,Toyota,Prius
1,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS
2,664760,21,71,black,black,male,4H42WR,Nissan,Altima

In [ ]:
# From the above drivers_licence table we got the license id checking whether this id and name matches with the suspects .
query = """ SELECT * FROM person WHERE  license_id= 183779; """
query = """ SELECT * FROM person WHERE  license_id= 423327; """
#query = """ SELECT * FROM person WHERE  license_id= 664760; """
pd.read_sql_query(query,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279

The Murder is Jeremy Bowers.

In [ ]:
# query ="""INSERT INTO solution VALUES (1, 'Jeremy Bowers');"""

query =       """SELECT value FROM solution;"""
pd.read_sql_query(query,conn)

                                                                                                                                                                                                                                                                                                                                                                                                value
0  Congrats, you found the murderer! But wait, there's more... If you think you're up for a challenge, try querying the interview transcript of the murderer to find the real villain behind this crime. If you feel especially confident in your SQL skills, try to complete this final step with no more than 2 queries. Use this same INSERT statement with your new suspect to check your answer.

In [ ]:
query = """SELECT * FROM interview WHERE person_id = 67318;"""
pd.read_sql_query(query,conn)

,person_id,transcript
0,67318,"I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5"" (65"") or 5'7"" (67""). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n"

In [ ]:
query = """SELECT * FROM drivers_license WHERE gender = "female" and hair_color = "red" and car_make = 'Tesla';"""
pd.read_sql_query(query,conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,202298,68,66,green,red,female,500123,Tesla,Model S
1,291182,65,66,blue,red,female,08CM64,Tesla,Model S
2,918773,48,65,black,red,female,917UU3,Tesla,Model S

In [ ]:
query = """ SELECT * FROM person WHERE  license_id= 918773; """
pd.read_sql_query(query,conn)

      id      name  license_id  address_number address_street_name        ssn
0  78881  Red Korb      918773             107         Camerata Dr  961388910

In [ ]:
query = """SELECT * FROM facebook_event_checkin WHERE event_name = 'SQL Symphony Concert' and date like '201712%' ORDER BY
person_id;"""
pd.read_sql_query(query,conn)

    person_id  event_id            event_name      date
0       11173      1143  SQL Symphony Concert  20171223
1       19260      1143  SQL Symphony Concert  20171214
2       19292      1143  SQL Symphony Concert  20171213
3       24397      1143  SQL Symphony Concert  20171208
4       24556      1143  SQL Symphony Concert  20171207
5       24556      1143  SQL Symphony Concert  20171221
6       24556      1143  SQL Symphony Concert  20171224
7       28582      1143  SQL Symphony Concert  20171220
8       28582      1143  SQL Symphony Concert  20171215
9       43366      1143  SQL Symphony Concert  20171207
10      58898      1143  SQL Symphony Concert  20171220
11      62596      1143  SQL Symphony Concert  20171225
12      67318      1143  SQL Symphony Concert  20171206
13      69325      1143  SQL Symphony Concert  20171206
14      69699      1143  SQL Symphony Concert  20171214
15      79312      1143  SQL Symphony Concert  20171203
16      81526      1143  SQL Symphony Concert  20171202
17      92343      1143  SQL Symphony Concert  20171212
18      99716      1143  SQL Symphony Concert  20171206
19      99716      1143  SQL Symphony Concert  20171212
20      99716      1143  SQL Symphony Concert  20171229